---
- name: Install prerequisite packages for ClickHouse
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: yes
  become: true

- name: Download ClickHouse GPG key and store it in keyring
  ansible.builtin.command: >
    bash -c "curl -fsSL 'https://packages.clickhouse.com/rpm/lts/repodata/repomd.xml.key'
    | gpg --dearmor -o {{ clickhouse_keyring_path }}"
  args:
    creates: "{{ clickhouse_keyring_path }}"
  become: true

- name: Get system architecture
  ansible.builtin.command: dpkg --print-architecture
  register: arch_cmd
  changed_when: false

- name: Set architecture fact
  set_fact:
    clickhouse_arch: "{{ arch_cmd.stdout }}"

- name: Add ClickHouse APT repository
  copy:
    dest: "{{ clickhouse_repo_path }}"
    content: |
      deb [signed-by={{ clickhouse_keyring_path }} arch={{ clickhouse_arch }}] https://packages.clickhouse.com/deb stable main
    mode: "0644"
  become: true

- name: Install ClickHouse packages
  apt:
    name: "{{ clickhouse_packages }}"
    state: present
    update_cache: yes
  become: true

- name: Ensure ClickHouse service is running
  service:
    name: clickhouse-server
    state: started
    enabled: yes
  become: true
